---
title: "Untitled"
output: github_document
date: "2025-09-24"
---

```{r set up}
library(tidyverse)
library(dplyr)
options(tibble.print_min = 5)
```

# Problem 1
## 1.1 pols_month
```{r}
pols_month = 
  read_csv(
    "./fivethirtyeight_datasets/pols-month.csv",
    na = c("NA", "", ".")) |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month","day"), sep = "-")|>
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    month = 
      case_match(
        month, 
        01 ~ "Jan", 
        02 ~ "Feb",
        03 ~ "Mar",
        04 ~ "Apr",
        05 ~ "May",
        06 ~ "Jun",
        07 ~ "Jul",
        08 ~ "Aug",
        09 ~ "Sep",
        10 ~ "Oct",
        11 ~ "Nov",
        12 ~ "Dec"),
    month = as.factor(month),
    year = as.factor(year)) |>
  relocate(prez_dem,prez_gop) |>
  pivot_longer(
    prez_dem:prez_gop,
    names_to = "president", 
    values_to = "prez_dem_or_prez_gop",
    names_prefix = "prez_" ) |>
  filter(prez_dem_or_prez_gop == 1)|>
  select(-day,-prez_dem_or_prez_gop)|>
  select(year,month,everything())
```

## 1.2 snp
```{r}
snp = 
  read_csv(
    "./fivethirtyeight_datasets/snp.csv",
    na = c("NA", "", ".")) |>
  janitor::clean_names() |>
  separate(date, into = c( "month","day","year"), sep = "/")|>
  mutate(
    month = as.integer(month),
    year = as.integer(year),
    month = 
      case_match(
        month, 
        1 ~ "Jan", 
        2 ~ "Feb",
        3 ~ "Mar",
        4 ~ "Apr",
        5 ~ "May",
        6 ~ "Jun",
        7 ~ "Jul",
        8 ~ "Aug",
        9 ~ "Sep",
        10 ~ "Oct",
        11 ~ "Nov",
        12 ~ "Dec")) |>
  mutate(
  year = case_when(
    year >= 50 ~ paste0("19", year), 
    year < 50 ~ paste0("20", year)),
    month = as.factor(month),
    year = as.factor(year)
)|>
  select(-day)|>
  select(year,month,everything())
```
## 1.3 unemployment
```{r}
unemployment = 
  read_csv(
    "./fivethirtyeight_datasets/unemployment.csv",
    na = c("NA", "", ".")) |>
  janitor::clean_names()|>
  pivot_longer(
    jan:dec,
    names_to = "month", 
    values_to = "unemployment") |>
   mutate(
    year = as.integer(year),
    month = 
      case_match(
        month, 
        "jan" ~ "Jan", 
        "feb" ~ "Feb",
        "mar" ~ "Mar",
        "apr" ~ "Apr",
        "may" ~ "May",
        "jun" ~ "Jun",
        "jul" ~ "Jul",
        "aug" ~ "Aug",
        "sep" ~ "Sep",
        "oct" ~ "Oct",
        "nov" ~ "Nov",
        "dec" ~ "Dec"),
    month = as.factor(month),
    year = as.factor(year)) |>
    select(year,month,everything())
```
## 1.4 join datasets
```{r}
datasets = 
  full_join(pols_month, snp, by = c("year","month")) |>
  full_join(unemployment, by = c("year","month"))
datasets
```

